//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAARemSerMod.Services.uk.ac.shu.hallam.webteach_net {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NAAWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class NAAWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNAAapplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNAAapplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNAAcourseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NAAWebService() {
            this.Url = global::NAARemSerMod.Services.Properties.Settings.Default.NAARemSerMod_Services_uk_ac_shu_hallam_webteach_net_NAAWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNAAapplicationsCompletedEventHandler GetNAAapplicationsCompleted;
        
        /// <remarks/>
        public event GetNAAapplicationCompletedEventHandler GetNAAapplicationCompleted;
        
        /// <remarks/>
        public event GetNAAcourseCompletedEventHandler GetNAAcourseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNAAapplications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Application[] GetNAAapplications() {
            object[] results = this.Invoke("GetNAAapplications", new object[0]);
            return ((Application[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNAAapplicationsAsync() {
            this.GetNAAapplicationsAsync(null);
        }
        
        /// <remarks/>
        public void GetNAAapplicationsAsync(object userState) {
            if ((this.GetNAAapplicationsOperationCompleted == null)) {
                this.GetNAAapplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNAAapplicationsOperationCompleted);
            }
            this.InvokeAsync("GetNAAapplications", new object[0], this.GetNAAapplicationsOperationCompleted, userState);
        }
        
        private void OnGetNAAapplicationsOperationCompleted(object arg) {
            if ((this.GetNAAapplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNAAapplicationsCompleted(this, new GetNAAapplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNAAapplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Application GetNAAapplication(int id) {
            object[] results = this.Invoke("GetNAAapplication", new object[] {
                        id});
            return ((Application)(results[0]));
        }
        
        /// <remarks/>
        public void GetNAAapplicationAsync(int id) {
            this.GetNAAapplicationAsync(id, null);
        }
        
        /// <remarks/>
        public void GetNAAapplicationAsync(int id, object userState) {
            if ((this.GetNAAapplicationOperationCompleted == null)) {
                this.GetNAAapplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNAAapplicationOperationCompleted);
            }
            this.InvokeAsync("GetNAAapplication", new object[] {
                        id}, this.GetNAAapplicationOperationCompleted, userState);
        }
        
        private void OnGetNAAapplicationOperationCompleted(object arg) {
            if ((this.GetNAAapplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNAAapplicationCompleted(this, new GetNAAapplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNAAcourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Application GetNAAcourse(string course) {
            object[] results = this.Invoke("GetNAAcourse", new object[] {
                        course});
            return ((Application)(results[0]));
        }
        
        /// <remarks/>
        public void GetNAAcourseAsync(string course) {
            this.GetNAAcourseAsync(course, null);
        }
        
        /// <remarks/>
        public void GetNAAcourseAsync(string course, object userState) {
            if ((this.GetNAAcourseOperationCompleted == null)) {
                this.GetNAAcourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNAAcourseOperationCompleted);
            }
            this.InvokeAsync("GetNAAcourse", new object[] {
                        course}, this.GetNAAcourseOperationCompleted, userState);
        }
        
        private void OnGetNAAcourseOperationCompleted(object arg) {
            if ((this.GetNAAcourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNAAcourseCompleted(this, new GetNAAcourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Application {
        
        private int applicationIdField;
        
        private int applicantIdField;
        
        private string courseNameField;
        
        private int universityIdField;
        
        private string personalStatementField;
        
        private string teacherReferenceField;
        
        private string teacherContactDetailsField;
        
        private string universityOfferField;
        
        private System.Nullable<bool> firmField;
        
        /// <remarks/>
        public int ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public int ApplicantId {
            get {
                return this.applicantIdField;
            }
            set {
                this.applicantIdField = value;
            }
        }
        
        /// <remarks/>
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        public int UniversityId {
            get {
                return this.universityIdField;
            }
            set {
                this.universityIdField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatement {
            get {
                return this.personalStatementField;
            }
            set {
                this.personalStatementField = value;
            }
        }
        
        /// <remarks/>
        public string TeacherReference {
            get {
                return this.teacherReferenceField;
            }
            set {
                this.teacherReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string TeacherContactDetails {
            get {
                return this.teacherContactDetailsField;
            }
            set {
                this.teacherContactDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string UniversityOffer {
            get {
                return this.universityOfferField;
            }
            set {
                this.universityOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Firm {
            get {
                return this.firmField;
            }
            set {
                this.firmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetNAAapplicationsCompletedEventHandler(object sender, GetNAAapplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNAAapplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNAAapplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetNAAapplicationCompletedEventHandler(object sender, GetNAAapplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNAAapplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNAAapplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetNAAcourseCompletedEventHandler(object sender, GetNAAcourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNAAcourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNAAcourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591